ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER SA_STOCK IDENTIFIED BY SA_STOCK
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE default;
GRANT connect, resource TO SA_STOCK;
GRANT UNLIMITED TABLESPACE TO SA_STOCK;
GRANT create TABLE TO SA_STOCK; 
GRANT system TO SA_STOCK; 
GRANT CREATE ANY DIRECTORY TO SA_STOCK;
GRANT SELECT, INSERT, UPDATE ON SA_STOCK TO PUBLIC;
