ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER SA_RETAIL IDENTIFIED BY SA_RETAIL
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE default;
GRANT connect, resource TO SA_RETAIL;
GRANT UNLIMITED TABLESPACE TO SA_RETAIL;
GRANT create TABLE TO SA_RETAIL; 
GRANT system TO SA_RETAIL; 
GRANT CREATE ANY DIRECTORY TO SA_RETAIL;
GRANT SELECT, INSERT, UPDATE ON SA_RETAIL TO PUBLIC;