ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER BL_3NF IDENTIFIED BY BL_3NF
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE default;
GRANT connect, resource TO BL_3NF;
GRANT UNLIMITED TABLESPACE TO BL_3NF;
GRANT create TABLE TO BL_3NF; 
GRANT system TO BL_3NF; 
GRANT CREATE ANY DIRECTORY TO BL_3NF;
GRANT SELECT, INSERT, UPDATE ON BL_3NF TO PUBLIC;
