CREATE OR REPLACE DIRECTORY ext_data_dir AS 'd:/WORK/Epam/Data_Engineering/DWH/learn/_practice/task_05/csv';

drop table ext_transaction_stock;

CREATE TABLE ext_transaction_stock
(
  SALE_ID VARCHAR2(4000),
  INVOICE VARCHAR2(4000),  
  STORE_ID VARCHAR2(4000),
  QUANTITY VARCHAR2(4000),
  PRICE  VARCHAR2(4000),
  CUSTOMER_ID VARCHAR2(4000),  
  INVOICE_DATE VARCHAR2(4000),
  SALE_AMOUNT VARCHAR2(4000),
  ADDRESS_ID VARCHAR2(4000),
  EMPLOYEE_ID VARCHAR2(4000),
  type_payment_id VARCHAR2(4000),
  BOOK_ID  VARCHAR2(4000)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY ext_data_dir
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE SKIP 1
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('b_transaction_400000.csv')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

select *
from ext_transaction_stock;

drop table ext_stock_customers;

CREATE TABLE ext_stock_customers
(
  CUSTOMER_ID VARCHAR2(4000),
  NAME_OF_ORGANIZATION VARCHAR2(4000),
  HEAD_OF_ORGANIZATION VARCHAR2(4000),
  EMAIL VARCHAR2(4000),
  IBAN VARCHAR2(4000),
  ADDRESS_ID VARCHAR2(4000)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY ext_data_dir
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE SKIP 1
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('customer_stock.csv')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;


select *
from ext_stock_customers;